import {StyleSheet} from 'react-native';

export const styles = StyleSheet.create({
  background: {
    width: 375,
    height: 767,
    backgroundColor: '#e5e5e5',
  },
  panah: {
    marginTop: 20,
    marginLeft: 20,
    marginBottom: 35,
  },
  judul: {
    marginLeft: 10,
    marginBottom: 25,
    fontWeight: 'bold',
    fontSize: 24,
    lineHeight: 33,
    color: '#373639',
  },
  have: {
    flexDirection: 'row',
    marginBottom: 25,
  },
  have1: {
    color: '#b0b0b0',
    fontSize: 14,
    lineHeight: 19,
    marginLeft: 10,
  },
  have2: {
    color: '#384dfe',
    fontSize: 14,
    lineHeight: 19,
    marginLeft: 5,
  },
  email: {
    marginRight: 305,
    marginBottom: 10,
    marginLeft: 10,
    fontSize: 14,
    lineHeight: 19,
    color: '#373639',
  },
  iemail: {
    marginRight: 15,
    marginLeft: 10,
    backgroundColor: '#fff',
    width: 327,
    height: 48,
    borderRadius: 6,
  },
  mnomer: {
    marginTop: 20,
    marginBottom: 10,
    marginLeft: 10,
    fontSize: 14,
    color: '#373639',
  },
  un: {
    flexDirection: 'row',
  },
  sp: {
    flexDirection: 'row',
    width: 125,
    height: 50,
    backgroundColor: '#fff',
    marginLeft: 10,
    borderRadius: 6,
  },
  sp1: {
    marginLeft: 10,
    marginTop: 17,
  },
  piker: {
    width: 100,
    height: 50,
  },
  nomer: {
    backgroundColor: '#fff',
    marginLeft: 10,
    width: 190,
    borderRadius: 6,
  },
  password: {
    marginTop: 20,
    marginBottom: 10,
    marginRight: 275,
    marginLeft: 10,
    fontSize: 14,
    lineHeight: 19,
    color: '#373639',
  },
  ipassword: {
    marginRight: 15,
    marginLeft: 10,
    backgroundColor: '#fff',
    width: 327,
    height: 48,
    borderRadius: 6,
  },
  eye: {
    position: 'absolute',
    top: 410,
    right: 50,
  },
  login: {
    width: 327,
    height: 48,
    borderRadius: 6,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#384dfe',
    marginTop: 40,
    marginRight: 10,
    marginLeft: 10,
  },
  tlogin: {
    color: '#fff',
    fontSize: 14,
    lineHeight: 22,
  },
  tforpass: {
    fontSize: 14,
    fontWeight: 'bold',
    lineHeight: 19,
    color: '#b0b0b0',
    marginTop: 20,
  },
  or: {
    fontSize: 12,
    marginLeft: 40,
    lineHeight: 16,
    color: '#b0b0b0',
    marginTop: 30,
  },
  logo: {
    flexDirection: 'row',
    marginTop: 20,
    marginLeft: 10,
  },

  fb: {marginRight: 30},
  google: {marginRight: 15},

  signup: {
    flexDirection: 'row',
    marginTop: 20,
  },
  s1: {
    color: '#b0b0b0',
    marginRight: 5,
  },
  s2: {color: '#384dfe'},
});
